apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: hcl
  name: patient-service
rules:
- apiGroups: [""] # "" = core API group
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
